version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./api-client/Dockerfile
    command: flask run --host=0.0.0.0
    ports:
      - "8090:5000"

  web:
    build:
      context: .
      dockerfile: ./sugus/Dockerfile
    ports:
      - "8080:80"
